bbs/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'bbs'
urlpatterns = [
    path('', views.free, name='free'),  # 전체 게시글
    path('<int:post_id>/', views.posting, name="posting"),  # 게시글
    path('new_post/<word>/', views.new_post),  # 게시글 새로 작성
    path('<int:post_id>/remove/', views.remove_post),  # 게시글 삭제

    path(
        'comment/create/<int:post_id>/', views.comment_create,
        name='comment_create'),  # 댓글 작성
    path(
        '<int:post_id>/<int:comment_id>/',
        views.comment_delete, name="comment_delete"),  # 댓글 삭제

    path('<int:uploadfile_id>/download/', views.download, name='download'),

] + static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # 추가 앱 최상단 경로
    path('main/', include('mainApp.urls')),
    path('index/', include('introductionApp.urls')),
    path('user/', include('userApp.urls')),
    path('free/', include('bbs.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userApp/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'user'

urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('login/', auth_views.LoginView.as_view(
        template_name='userApp/login.html'), name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path("mypage/", views.mypage, name='mypage'),
    path("delete/", views.delete, name='delete'),
    path("edit_profile/", views.edit_profile, name='edit_profile')
]

userApp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class Users(AbstractUser):
    full_name = models.CharField(max_length=100)
    first_name = None
    last_name = None
    email = models.EmailField(blank=False, unique=True)
    username = models.CharField(max_length=100, blank=False, unique=True)


class UserEmotions(models.Model):
    user = models.ForeignKey(Users, on_delete=models.CASCADE)
    terrified = models.IntegerField(default=0)
    surprised = models.IntegerField(default=0)
    angry = models.IntegerField(default=0)
    sad = models.IntegerField(default=0)
    neutral = models.IntegerField(default=0)
    happy = models.IntegerField(default=0)
    hate = models.IntegerField(default=0)

userApp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import Users


class SignupForm(UserCreationForm):
    full_name = forms.CharField(
        max_length=50, required=True, help_text="이름을 입력해주세요")
    email = forms.EmailField(
        max_length=100, required=True, help_text="유효한 이메일을 입력해주세요")

    class Meta:
        model = Users
        fields = ['full_name', 'username', 'password1', 'password2', 'email']

        labels = {
            'username': '아이디',
            'password1': '비밀번호',
            'email': '이메일',
            'full_name': '이름',
        }


class EditProfileForm(UserChangeForm):
    full_name = forms.CharField(
        max_length=50, required=True, help_text="이름을 입력해주세요")
    email = forms.EmailField()

    class Meta:
        model = Users
        fields = ['full_name', 'email']

userApp/views.py
from django.shortcuts import render, redirect
from userApp.forms import SignupForm, EditProfileForm
from django.contrib import auth

from .models import Users, UserEmotions


def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()

            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            auth.authenticate(username=username, password=raw_password)
            # auth.login(request, user)

            UserEmotions.objects.create(
                user=Users.objects.get(username=username)
            )

            return redirect("user:login")
    else:
        form = SignupForm()
    return render(request, 'userApp/signup.html', {'form': form})


def mypage(request):
    user = request.user
    context = {}

    context['user'] = user

    return render(request, "userApp/mypage.html", context)


def edit_profile(request):
    user = request.user

    if request.method == "POST":
        form = EditProfileForm(data=request.POST, instance=user)

        if form.is_valid():
            form.save()
            return redirect("user:mypage")
    else:
        form = EditProfileForm(instance=user)

    return render(request, "userApp/edit_profile.html", {'form': form})


def edit_password(request):
    pass


def delete(request):
    username = request.user
    user = Users.objects.get(username=username)

    user.delete()
    auth.logout(request)
    return redirect("main")

userApp/templates/userApp/edit_profile.html
{% extends 'mainApp/base.html' %}
{% load static %}

{% block edge %}
        <!-- Content -->

    <!-- Content -->

    <div class="container-xxl">
        <div class="authentication-wrapper authentication-basic container-p-y">
          <div class="authentication-inner">
            <!-- Register Card -->
            <div class="card">
              <div class="card-body">
                <!-- Logo -->
                <div class="app-brand justify-content-center">
                  <div class="col-3">
                    <img src="{%static 'img/logo/main_logo.png'%}" class='img-fluid'/>
                  </div>
                </div>
                <!-- /Logo -->
                <div class="row justify-content-center">
                  <div class="col-4">

                    <h4 class="mb-2">Edit Profile</h4>
      
                    <form id="formAuthentication" class="mb-3" action="{% url 'user:edit_profile' %}" method="POST">
                      {% csrf_token %}
                      {% if error %}
                        <strong>{{ error }} </strong>
                      {% endif%}
    
                      {% if form.errors %}
                      <div class="alert alert-primary alert-dismissible" role="alert">
    
                        {% for field in form %}
                          {% for error in field.errors %}
                            {{ field.label}} : {{ error }}<br>
                          {% endfor %}
                        {% endfor %}
                        
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                      </div>
                      {% endif %}
                    
                      <div class="mb-3">
                        <label for="full_name" class="form-label">name</label>
                        <input
                          type="text"
                          class="form-control"
                          id="full_name"
                          name="full_name"
                          placeholder="Enter your full name"
                          autofocus
                        />
                      </div>
                      <div class="mb-3">
                        <label for="email" class="form-label">Email</label>
                        <input type="text" class="form-control" id="email" name="email" placeholder="Enter your email" />
                      </div>
                      <div class="mb-3">
                        <button class="btn btn-primary d-grid w-100" type="submit" value="signup">Edit</button>
                      </div>
                      </form>
                  </div>
                </div>
              </div>
            </div>
            <!-- Register Card -->
          </div>
        </div>
      </div>
  
      <!-- / Content -->

{% endblock edge %}

userApp/templates/userApp/login.html
{% extends 'mainApp/base.html' %}
{% load static %}

{% block edge %}
<body>
    <!-- Content -->

    <div class="container-xxl">
      <div class="authentication-wrapper authentication-basic container-p-y">
        <div class="authentication-inner">
          <!-- Register -->
          <div class="card">
            <div class="card-body">
              
              <!-- Logo -->
              <div class="app-brand justify-content-center">
                <div class="col-3">
                  <img src="{%static 'img/logo/main_logo.png'%}" class='img-fluid'/>
                </div>
              </div>
              <!-- /Logo -->
              <div class="row justify-content-center">
                <div class="col-4">
                  <h4 class="mb-2">How do you feel today? 👋</h4>
                  <p class="mb-4">오늘의 기분을 기록하러 가볼까요?</p>
                  
                  <form class="mb-3" action="{% url 'user:login' %}" method="POST">
                    {% csrf_token %}
                    {% include 'userApp/detail/form_error.html'%}
                    <div class="mb-3">
                      <label for="email" class="form-label">Username</label>
                      <input
                        type="text"
                        class="form-control"
                        id="username"
                        name="username"
                        placeholder="Enter your username"
                        autofocus
                      />
                    </div>
                    <div class="mb-3 form-password-toggle">
                      <div class="d-flex justify-content-between">
                        <label class="form-label" for="password">Password</label>
                        {% comment %} <a href="auth-forgot-password-basic.html">
                          <small>Forgot Password?</small>
                        </a> {% endcomment %}
                      </div>
                      <div class="input-group input-group-merge">
                        <input
                          type="password"
                          id="password"
                          class="form-control"
                          name="password"
                          placeholder="&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;"
                          aria-describedby="password"
                        />
                        <span class="input-group-text cursor-pointer"><i class="bx bx-hide"></i></span>
                      </div>
                    </div>
                    <div class="mb-3">
                      <button class="btn btn-primary d-grid w-100" value="login" id="login" type="submit">Sign in</button>
                    </div>
                  </form>
                </div>
              </div>

              <p class="text-center">
                <span>아직 회원이 아니신가요?</span>
                <a href="{% url 'user:signup'%}">
                  <span>회원 가입하러 고!</span>
                </a>
              </p>
            </div>
          </div>
          <!-- /Register -->
        </div>
      </div>
    </div>

    <!-- / Content -->


{% endblock edge %}

userApp/templates/userApp/mypage.html
{% extends 'mainApp/base.html' %}
<h1> mypage </h1>

이름: {{ user.full_name }}<br>
이메일: {{ user.email }}<br>
가입일: {{ user.date_joined }}<br>



{% load static %}

{% block edge %}
    <!-- Layout wrapper -->
    <div class="layout-wrapper layout-content-navbar">
      <div class="layout-container">
        <!-- Menu -->

        <aside id="layout-menu" class="layout-menu menu-vertical menu bg-menu-theme">
          <div class="d-flex justify-content-center">

            <a href="{% url 'main' %}" class="app-brand-link">
              <img src="{%static 'img/logo/main_logo.png'%}" class='img-fluid'/>

            </a>

            <a href="javascript:void(0);" class="layout-menu-toggle menu-link text-large ms-auto d-block d-xl-none">
              <i class="bx bx-chevron-left bx-sm align-middle"></i>
            </a>
          </div>

          <div class="menu-inner-shadow"></div>

          <ul class="menu-inner py-1">
            <!-- Dashboard -->
            <li class="menu-item">
              <a href="{% url 'main' %}" class="menu-link">
                <i class="menu-icon tf-icons bx bx-home-circle"></i>
                <div data-i18n="Analytics">메인 페이지</div>
              </a>
            </li>
            <li class="menu-item">
              <a href="{% url 'bbs:free' %}" class="menu-link">
                  <i class="menu-icon tf-icons bx bx-list-ul bx-tada-hover"></i>
                  <div data-i18n="Analytics">자유게시판</div>
              </a>
            </li>

            <!-- Layouts -->

            <li class="menu-item">
              <a href="javascript:void(0);" class="menu-link menu-toggle">
                <i class="menu-icon tf-icons bx bx-dock-top"></i>
                <div data-i18n="Account Settings">상세 보기</div>
              </a>
              <ul class="menu-sub">
                <li class="menu-item">
                  <a href="{% url 'calendar' %}" class="menu-link">
                    <i class="menu-icon tf-icons bx bx-calendar"></i>
                    <div data-i18n="Boxicons">달력으로 보기</div>
                  </a>
                </li>
                <li class="menu-item">
                  <a href="{% url 'chart' %}" class="menu-link">
                    <i class="menu-icon tf-icons bx bx-bar-chart-alt-2"></i>
                    <div data-i18n="Boxicons">차트로 보기</div>
                  </a>
                </li>
              </ul>
            </li>


            <li class="menu-item">

            </li>
            <li class="menu-item">

            </li>
            <li class="menu-item">
              
            </li>
            <li class="menu-item">
              <a href="{% url 'remind'%}" class="menu-link">
                <i class="menu-icon tf-icons bx bx-history"></i>
                <div data-i18n="Boxicons">추억 돌아보기</div>
              </a>
            </li>
            <li class="menu-item">
              <a href="{% url 'tamagotchi' %}" class="menu-link">
                <i class="menu-icon tf-icons bx bx-home-smile"></i>
                <div data-i18n="Boxicons">알 키우기</div>
              </a>
            </li>
            <li class="menu-item">
              <a href="{% url 'share' %}" class="menu-link">
                <i class="menu-icon tf-icons bx bx-cool"></i>
                <div data-i18n="Boxicons">다른 사람은?</div>
              </a>
            </li>
          </ul>
        </aside>
        <!-- / Menu -->

        <!-- Layout container -->
        <div class="layout-page">
          <!-- Navbar -->
          <nav
            class="layout-navbar container-xxl navbar navbar-expand-xl navbar-detached align-items-center bg-navbar-theme"
            id="layout-navbar"
          >
            <div class="layout-menu-toggle navbar-nav align-items-xl-center me-3 me-xl-0 d-xl-none">
              <a class="nav-item nav-link px-0 me-xl-4" href="javascript:void(0)">
                <i class="bx bx-menu bx-sm"></i>
              </a>
            </div>

            <div class="navbar-nav-right d-flex align-items-center" id="navbar-collapse">
              <!-- Search -->
              <div class="navbar-nav align-items-center">
                <div class="navbar-nav align-items-center">
                  <div class="nav-item d-flex align-items-center">
                    <span class="badge bg-primary" id='CurrentTime' onload='showTime()'></span>
                  <script>
                    function showTime(){
                      var date = new Date();
                      var h = date.getHours(); // 0 - 23
                      var m = date.getMinutes(); // 0 - 59
                      var s = date.getSeconds(); // 0 - 59
                      var session = "AM";
                      
                      if(h == 0){
                          h = 12;
                      }
                      
                      if(h > 12){
                          h = h - 12;
                          session = "PM";
                      }
                      
                      h = (h < 10) ? "0" + h : h;
                      m = (m < 10) ? "0" + m : m;
                      s = (s < 10) ? "0" + s : s;
                      
                      var time = '현재 시각 :' + h + ":" + m + ":" + s + " " + session;
                      document.getElementById("CurrentTime").innerText = time;
                      document.getElementById("CurrentTime").textContent = time;
                      
                      setTimeout(showTime, 1000);
                      
                  }
                  
                  showTime();
                  </script>
                  </div>
                </div>
              </div>
              <!-- /Search -->

              <ul class="navbar-nav flex-row align-items-center ms-auto">
                <!-- User -->
                
                <li class="nav-item navbar-dropdown dropdown-user dropdown">
                  <a class="nav-link dropdown-toggle hide-arrow" href="javascript:void(0);" data-bs-toggle="dropdown">
                    <div class="avatar avatar-online">
                      <img src="{% static 'mainApp/assets/img/favicon/7.png'%}" alt class="w-px-40 h-auto rounded-circle" />
                    </div>
                  </a>
                  <ul class="dropdown-menu dropdown-menu-end">
                    <li>
                      <a class="dropdown-item" href="#">
                        <div class="d-flex">
                          
                          <div class="flex-shrink-0 me-3">
                            <div class="avatar avatar-online">
                              <img src="{% static 'mainApp/assets/img/favicon/7.png'%}" alt class="w-px-40 h-auto rounded-circle" />
                            </div>
                          </div>
                          <div class="flex-grow-1">
                            {% if user.is_authenticated %}
                              <span class="fw-semibold d-block">{{ user.username }}</span>
                              <small class="text-muted">User</small>
                            {% endif %}
                          </div>
                        </div>
                      </a>
                    </li>
                    <li>
                      <div class="dropdown-divider"></div>
                    </li>
                    <li>
                      <a class="dropdown-item" href="{% url 'user:mypage' %}">
                        <i class="bx bx-user me-2"></i>
                        <span class="align-middle">My Profile</span>
                      </a>
                    </li>
                    
                    <li>
                      <div class="dropdown-divider"></div>
                    </li>
                    <li>
                      <a class="dropdown-item" href="{% url 'user:logout' %}">
                        {% if user.is_authenticated %}
                        <i class="bx bx-power-off me-2"></i>
                        <span class="align-middle">Log Out</span>
                        {% else %}
                        <i class="bx bx-power-off me-2"></i>
                        <span class="align-middle">Log In</span>
                        {% endif %}
                      </a>
                    </li>
                  </ul>
                </li>
                <!--/ User -->
              </ul>
            </div>
          </nav>

          <!-- / Navbar -->



          <!-- Content wrapper -->
          <div class="content-wrapper">
            <!-- Content -->

            <div class="container-xxl flex-grow-1 container-p-y">
              <!-- {% block content %} -->
  
                <div class="row">
                  <div class="col-md-12">
                    <br><br>
                    <ul class="nav nav-pills flex-column flex-md-row mb-3">
                      <li class="nav-item">
                        <h1 style="font-family: 'Dongle', sans-serif; font-size : 70px; font-weight: bold;"> Account </h1>
                      </li>
                    </ul>
                    <br>
                    <div class="card mb-4">
                      <h5 class="card-header">Profile Details</h5>
                      <!-- Account -->
                      <div class="card-body">
                        <div class="d-flex align-items-start align-items-sm-center gap-4">
                          <img
                            src="{% static 'mainApp/assets/img/favicon/7.png'%}"
                            alt="user-avatar"
                            class="d-block rounded"
                            height="100"
                            width="100"
                            id="uploadedAvatar"
                          />
                          <div class="button-wrapper">
                            
                          </div>
                        </div>
                      </div>
                      <hr class="my-0" />
                      <div class="card-body">
                          <div class="row">
                            <div class="mb-3 col-md-6">
                              <label for="firstName" class="form-label">Name</label>
                              <span class="form-control" />{{ user.full_name }}</span>
                            </div>
                            <div class="mb-3 col-md-6">
                              <label for="lastName" class="form-label">e-mail</label>
                              <span class="form-control" />{{ user.email }}</span>
                            </div>
                          </div>
                          <div class="row">
                            <div class="mb-3 col-md-6">
                              <label for="firstName" class="form-label">가입일</label>
                              <span class="form-control" />{{ user.date_joined }}</span>
                            </div>
                            <div class="mb-3 col-md-6">
                              <label for="lastName" class="form-label">빈 값</label>
                              <span class="form-control" /> - </span>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col">
                      </div>
                      <div class="col">
                      </div>
                      <div class="col">
                      </div>
                      <div class="col">
                      </div>
                      
                      <div class="col">
                      
                    
                    <a href={% url "user:edit_profile" %}><button type="button" class="btn btn-dark">회원정보 수정</button></a>
                    <a href={% url "user:delete" %}><button type="button" class="btn btn-danger">회원탈퇴</button></a>
                    </div>
                  </div>
                  </div>



























              <!-- {% endblock content %} -->
            </div>
            <!-- / Content -->

            <!-- Footer -->
            <footer class="content-footer footer bg-footer-theme">
              <div class="container-xxl d-flex flex-wrap justify-content-between py-2 flex-md-row flex-column">
                <div class="mb-2 mb-md-0">
                  ©
                  <script>
                    document.write(new Date().getFullYear());
                  </script>
                  , made with ❤️ by
                  Aivle School <strong>AI 수도권 1반 1조</strong>
                </div>
                <div>
                  이대용 | 전현근 | 천명철 | 편승희 | 홍지의
                </div>
              </div>
            </footer>
            <!-- / Footer -->

            <div class="content-backdrop fade"></div>
          </div>
          <!-- Content wrapper -->
        </div>
        <!-- / Layout page -->
      </div>

      <!-- Overlay -->
      <div class="layout-overlay layout-menu-toggle"></div>
    </div>
    <!-- / Layout wrapper -->
{% endblock edge %}

userApp/templates/userApp/signup.html
{% extends 'mainApp/base.html' %}
{% load static %}

{% block edge %}
        <!-- Content -->

    <!-- Content -->

    <div class="container-xxl">
        <div class="authentication-wrapper authentication-basic container-p-y">
          <div class="authentication-inner">
            <!-- Register Card -->
            <div class="card">
              <div class="card-body">
                <!-- Logo -->
                <div class="app-brand justify-content-center">
                  <div class="col-3">
                    <img src="{%static 'img/logo/main_logo.png'%}" class='img-fluid'/>
                  </div>
                </div>
                <!-- /Logo -->
                <div class="row justify-content-center">
                  <div class="col-4">

                    <h4 class="mb-2">Join us!</h4>
                    <p class="mb-4">We will fill your life with happiness</p>
      
                    <form id="formAuthentication" class="mb-3" action="{% url 'user:signup' %}" method="POST">
                      {% csrf_token %}
                      {% if error %}
                        <strong>{{ error }} </strong>
                      {% endif%}
    
                      {% if form.errors %}
                      <div class="alert alert-primary alert-dismissible" role="alert">
    
                        {% for field in form %}
                          {% for error in field.errors %}
                            {{ field.label}} : {{ error }}<br>
                          {% endfor %}
                        {% endfor %}
                        
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                      </div>
                      {% endif %}
    
                      <div class="mb-3">
                        <label for="username" class="form-label">Username</label>
                        <input
                          type="text"
                          class="form-control"
                          id="username"
                          name="username"
                          placeholder="Enter your username"
                          autofocus
                        />
                      </div>
                      
    
                      <div class="mb-3 form-password-toggle">
                        <label class="form-label" for="password">Password</label>
                        <div class="input-group input-group-merge">
                          <input
                            type="password"
                            id="password1"
                            class="form-control"
                            name="password1"
                            placeholder="&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;"
                            aria-describedby="password"
                          />
                          <span class="input-group-text cursor-pointer"><i class="bx bx-hide"></i></span>
                        </div>
                      </div>
                      <div class="mb-3 form-password-toggle">
                        <label class="form-label" for="password2">Re-enter Password</label>
                        <div class="input-group input-group-merge">
                          <input
                            type="password"
                            id="password2"
                            class="form-control"
                            name="password2"
                            placeholder="&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;"
                            aria-describedby="password"
                          />
                          <span class="input-group-text cursor-pointer"><i class="bx bx-hide"></i></span>
                        </div>
                      </div>
                      <div class="mb-3">
                        <label for="full_name" class="form-label">name</label>
                        <input
                          type="text"
                          class="form-control"
                          id="full_name"
                          name="full_name"
                          placeholder="Enter your full name"
                          autofocus
                        />
                      </div>
                      <div class="mb-3">
                        <label for="email" class="form-label">Email</label>
                        <input type="text" class="form-control" id="email" name="email" placeholder="Enter your email" />
                      </div>
                      <div class="mb-3">
                        <button class="btn btn-primary d-grid w-100" type="submit" value="signup">Sign up</button>
                      </div>
                      </form>
                  </div>
                </div>
                
                <p class="text-center">
                  <span>이미 계정이 있으신가요?</span>
                  <a href="{% url 'user:login'%}">
                    <span>로그인하러 고!</span>
                  </a>
                </p>
              </div>
            </div>
            <!-- Register Card -->
          </div>
        </div>
      </div>
  
      <!-- / Content -->

{% endblock edge %}

userApp/templates/userApp/signup_test.html
<h1>회원가입</h1>

<form method="POST" action={% url 'user:signup' %}>
    {% csrf_token %}

    {% for field in form %}
        <p>
            {{ field.label }}<br>
            {{ field }}
            {% if field.help_text %}
                <small style="color:grey">{{field.help_text}}</small>
            {% endif %}

            {% for error in field.errors%}
                <p style="color:red">{{error}}</p>
            {% endfor %}
        </p>
    {% endfor %}

    <button type='submit'>signup</button>
</form>

</form>