bbs/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'bbs'
urlpatterns = [
    path('', views.free, name='free'),  # 전체 게시글
    path('<int:post_id>/', views.posting, name="posting"),  # 게시글
    path('new_post/<word>/', views.new_post),  # 게시글 새로 작성
    path('<int:post_id>/remove/', views.remove_post),  # 게시글 삭제

    path(
        'comment/create/<int:post_id>/', views.comment_create,
        name='comment_create'),  # 댓글 작성
    path(
        '<int:post_id>/<int:comment_id>/',
        views.comment_delete, name="comment_delete"),  # 댓글 삭제

    path('<int:uploadfile_id>/download/', views.download, name='download'),

] + static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # 추가 앱 최상단 경로
    path('main/', include('mainApp.urls')),
    path('index/', include('introductionApp.urls')),
    path('user/', include('userApp.urls')),
    path('free/', include('bbs.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userApp/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'user'

urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('login/', auth_views.LoginView.as_view(
        template_name='userApp/login.html'), name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path("mypage/", views.mypage, name='mypage'),
    path("delete/", views.delete, name='delete'),
    path("edit_profile/", views.edit_profile, name='edit_profile')
]

bbs/models.py
from django.db import models


class Post(models.Model):
    postname = models.CharField(max_length=50)
    contents = models.TextField()
    views = models.IntegerField(default='0')
    code_edit = models.TextField(blank=True)
    writer = models.CharField(max_length=150, blank=True)

    def __str__(self):
        return self.postname

    def summary(self):
        return self.contents[:80]


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()

    def __str__(self):
        return self.post


class UploadFile(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    file = models.FileField(upload_to='%Y/%m/%d')

    def __str__(self):
        return self.post

bbs/forms.py
from django import forms
from .models import Comment
from .models import Post
from .models import UploadFile


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['postname', 'contents', 'code_edit']
        labels = {
            'postname': '제목',
            'contents': '내용',
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        labels = {
            'content': '답변내용',
        }


class UploadFileForm(forms.ModelForm):
    class Meta:
        model = UploadFile
        fields = ['file']

bbs/views.py
from .forms import UploadFileForm
from django.shortcuts import render, redirect
from django.shortcuts import get_object_or_404
from django.core.paginator import Paginator
from config import settings
import os
from .models import UploadFile
from django.http import HttpResponse
import urllib
from django.utils import timezone
from .models import Comment
from .forms import CommentForm
from .models import Post


def free(request):
    postlist = Post.objects.order_by('-id')
    page = request.GET.get('page', '1')
    # 한 페이지에 출력할 갯수
    paginator = Paginator(postlist, 9)
    page_obj = paginator.get_page(page)

    return render(request, 'bbs/free.html', {'postlist': page_obj})


def posting(request, post_id):
    post = Post.objects.get(id=post_id)
    post.views += 1
    post.save()
    context = {
        'post': post
    }
    return render(request, 'bbs/posting.html', context)


def new_post(request, word):
    if request.method == 'POST' and request.POST['postname'] != '':
        new_article = Post.objects.create(
            postname=request.POST['postname'],
            contents=request.POST['contents'],
            code_edit=request.POST.get('code_edit', ''),
            writer=word
        )
        new_article.save()
        if(request.FILES):
            form = UploadFileForm(request.POST, request.FILES)
            if form.is_valid():
                uploadFile = form.save(commit=False)
                uploadFile.post = new_article
                uploadFile.save()
                return redirect('/free/')
        return redirect('/free/')
    elif request.method == 'POST' and request.POST['postname'] == '':
        context = {'written': request.POST['contents']}
        return render(request, 'bbs/new_post.html', context)
    else:
        form = UploadFileForm()
    return render(request, 'bbs/new_post.html')


def download(request, uploadfile_id):
    uploadFile = UploadFile.objects.get(id=uploadfile_id)
    if request.method == "GET":
        filepath = str(
            settings.BASE_DIR) + ('/media/%s' % uploadFile.file.name)
        filename = urllib.parse.quote(
            os.path.basename(filepath).encode('utf-8'))
        print(filename)
        with open(filepath, 'rb') as f:
            response = HttpResponse(f, content_type='application/octet-stream')
            response[
                'Content-Disposition'
                ] = 'attachment; filename*=UTF-8\'\'%s' % filename
            # response['Content-Disposition'] = 'attachment; filename=test.jpg'
            return response


def remove_post(request, post_id):
    post = Post.objects.get(pk=post_id)
    if request.method == 'POST':
        post.delete()
        return redirect('/free/')
    return render(request, 'bbs/remove_post.html', {'Post': post})


def comment_create(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.create_date = timezone.now()
            comment.post = post
            comment.save()
            return redirect('bbs:posting', post_id=post.id)
    else:
        form = CommentForm()
    context = {'post': post, 'form': form}
    return render(request, 'bbs/posting.html', context)


def comment_delete(request, post_id, comment_id):
    post = get_object_or_404(Post, pk=post_id)
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.method == "GET":
        comment.delete()
        return redirect('bbs:posting', post_id=post.id)
    context = {'post': post, 'form': Comment.objects.all()}
    return render(request, 'bbs/posting.html', context)

bbs/templates/bbs/base.html
{% extends 'mainApp/base.html' %}
{% load static %}

{% block edge %}
    <!-- Layout wrapper -->
    <div class="layout-wrapper layout-content-navbar">
      <div class="layout-container">
        <!-- Menu -->

        <aside id="layout-menu" class="layout-menu menu-vertical menu bg-menu-theme">
          <div class="d-flex justify-content-center">

            <a href="{% url 'main' %}" class="app-brand-link">
              <img src="{%static 'img/logo/main_logo.png'%}" class='img-fluid'/>

            </a>

            <a href="javascript:void(0);" class="layout-menu-toggle menu-link text-large ms-auto d-block d-xl-none">
              <i class="bx bx-chevron-left bx-sm align-middle"></i>
            </a>
          </div>

          <div class="menu-inner-shadow"></div>

          <ul class="menu-inner py-1">
            <!-- Dashboard -->
            <li class="menu-item">
              <a href="{% url 'main' %}" class="menu-link">
                <i class="menu-icon tf-icons bx bx-home-circle bx-tada-hover"></i>
                <div data-i18n="Analytics">메인 페이지</div>
              </a>
            </li>
            <li class="menu-item active">
                <a href="{% url 'bbs:free' %}" class="menu-link">
                    <i class="menu-icon tf-icons bx bx-list-ul bx-tada-hover"></i>
                    <div data-i18n="Analytics">자유게시판</div>
                </a>
            </li>

            <!-- Layouts -->

            <li class="menu-item">
              <a href="javascript:void(0);" class="menu-link menu-toggle">
                <i class="menu-icon tf-icons bx bx-dock-top bx-tada-hover"></i>
                <div data-i18n="Account Settings">상세 보기</div>
              </a>
              <ul class="menu-sub">
                <li class="menu-item">
                  <a href="{% url 'calendar' %}" class="menu-link">
                    <i class="menu-icon tf-icons bx bx-calendar bx-tada-hover"></i>
                    <div data-i18n="Boxicons">달력으로 보기</div>
                  </a>
                </li>
                <li class="menu-item">
                  <a href="{% url 'chart' %}" class="menu-link">
                    <i class="menu-icon tf-icons bx bx-bar-chart-alt-2 bx-tada-hover"></i>
                    <div data-i18n="Boxicons">차트로 보기</div>
                  </a>
                </li>
                {% comment %} <li class="menu-item">
                  <a href="{% url 'media' %}" class="menu-link">
                    <i class="menu-icon tf-icons bx bx-music bx-tada-hover"></i>
                    <div data-i18n="Boxicons">Media 추천보기</div>
                  </a>
                </li> {% endcomment %}
              </ul>
            </li>


            <li class="menu-item">

            </li>
            <li class="menu-item">

            </li>
            <li class="menu-item">
              
            </li>
            <li class="menu-item">
              <a href="{% url 'remind'%}" class="menu-link">
                <i class="menu-icon tf-icons bx bx-history bx-tada-hover"></i>
                <div data-i18n="Boxicons">추억 돌아보기</div>
              </a>
            </li>
            <li class="menu-item">
              <a href="{% url 'tamagotchi' %}" class="menu-link">
                <i class="menu-icon tf-icons bx bx-home-smile bx-tada-hover"></i>
                <div data-i18n="Boxicons">알 키우기</div>
              </a>
            </li>
            <li class="menu-item">
              <a href="{% url 'share' %}" class="menu-link">
                <i class="menu-icon tf-icons bx bx-cool bx-tada-hover"></i>
                <div data-i18n="Boxicons">다른 사람은?</div>
              </a>
            </li>
          </ul>
        </aside>
        <!-- / Menu -->

        <!-- Layout container -->
        <div class="layout-page">
          <!-- Navbar -->
          <nav
            class="layout-navbar container-xxl navbar navbar-expand-xl navbar-detached align-items-center bg-navbar-theme"
            id="layout-navbar"
          >
            <div class="layout-menu-toggle navbar-nav align-items-xl-center me-3 me-xl-0 d-xl-none">
              <a class="nav-item nav-link px-0 me-xl-4" href="javascript:void(0)">
                <i class="bx bx-menu bx-sm"></i>
              </a>
            </div>

            <div class="navbar-nav-right d-flex align-items-center" id="navbar-collapse">
              <!-- Search -->
              <div class="navbar-nav align-items-center">
                <div class="navbar-nav align-items-center">
                  <span class="badge bg-primary" id='CurrentTime' onload='showTime()'></span>
                  <script>
                    function showTime(){
                      var date = new Date();
                      var h = date.getHours(); // 0 - 23
                      var m = date.getMinutes(); // 0 - 59
                      var s = date.getSeconds(); // 0 - 59
                      var session = "AM";
                      
                      if(h == 0){
                          h = 12;
                      }
                      
                      if(h > 12){
                          h = h - 12;
                          session = "PM";
                      }
                      
                      h = (h < 10) ? "0" + h : h;
                      m = (m < 10) ? "0" + m : m;
                      s = (s < 10) ? "0" + s : s;
                      
                      var time = '현재 시각 :' + h + ":" + m + " " + session;
                      document.getElementById("CurrentTime").innerText = time;
                      document.getElementById("CurrentTime").textContent = time;
                      
                      setTimeout(showTime, 1000);
                      
                  }
                  
                  showTime();
                  </script>
                </div>
              </div>
              <!-- /Search -->

              <ul class="navbar-nav flex-row align-items-center ms-auto">
                <!-- User -->
                
                <li class="nav-item navbar-dropdown dropdown-user dropdown">
                  <a class="nav-link dropdown-toggle hide-arrow" href="javascript:void(0);" data-bs-toggle="dropdown">
                    <div class="avatar avatar-online">
                      <img src="{% static 'mainApp/assets/img/favicon/7.png'%}" alt class="w-px-40 h-auto rounded-circle" />
                    </div>
                  </a>
                  <ul class="dropdown-menu dropdown-menu-end">
                    <li>
                      <a class="dropdown-item" href="#">
                        <div class="d-flex">
                          
                          <div class="flex-shrink-0 me-3">
                            <div class="avatar avatar-online">
                              <img src="{% static 'mainApp/assets/img/favicon/7.png'%}" alt class="w-px-40 h-auto rounded-circle" />
                            </div>
                          </div>
                          <div class="flex-grow-1">
                            {% if user.is_authenticated %}
                              <span class="fw-semibold d-block">{{ user.username }}</span>
                              <small class="text-muted">User</small>
                            {% endif %}
                          </div>
                        </div>
                      </a>
                    </li>
                    <li>
                      <div class="dropdown-divider"></div>
                    </li>
                    <li>
                      <a class="dropdown-item" href="{% url 'user:mypage' %}">
                        <i class="bx bx-user me-2"></i>
                        <span class="align-middle">My Profile</span>
                      </a>
                    </li>
                  
                    <li>
                      <div class="dropdown-divider"></div>
                    </li>
                    <li>
                      <a class="dropdown-item" href="{% url 'user:logout' %}">
                        {% if user.is_authenticated %}
                        <i class="bx bx-power-off me-2"></i>
                        <span class="align-middle">Log Out</span>
                        {% else %}
                        <i class="bx bx-power-off me-2"></i>
                        <span class="align-middle">Log In</span>
                        {% endif %}
                      </a>
                    </li>
                  </ul>
                </li>
                <!--/ User -->
              </ul>
            </div>
          </nav>

          <!-- / Navbar -->

          <script src="https://cdn.jsdelivr.net/npm/chart.js@3.7.1/dist/chart.min.js"></script>

          <!-- Content wrapper -->
          <div class="content-wrapper">
            <!-- Content -->
            {% block content %}

            {% endblock content %}
            <!-- / Content -->
            <!-- Footer -->
            <footer class="content-footer footer bg-footer-theme">
              <div class="container-xxl d-flex flex-wrap justify-content-between py-2 flex-md-row flex-column">
                <div class="mb-2 mb-md-0">
                  ©
                  <script>
                    document.write(new Date().getFullYear());
                  </script>
                  , made with ❤️ by
                  Aivle School <strong>AI 수도권 1반 1조</strong>
                </div>
                <div>
                  이대용 | 전현근 | 천명철 | 편승희 | 홍지의
                </div>
              </div>
            </footer>
            <!-- / Footer -->

            <div class="content-backdrop fade"></div>
          </div>
          <!-- Content wrapper -->
        </div>
        <!-- / Layout page -->
      </div>

      <!-- Overlay -->
      <div class="layout-overlay layout-menu-toggle"></div>
    </div>
    <!-- / Layout wrapper -->
    <!--anime.js와 다마고찌 셋팅-->
    <script src='https://cdnjs.cloudflare.com/ajax/libs/animejs/3.1.0/anime.min.js'></script>
    <script  src="{% static 'mainApp/assets/js/tamagotchi.js'%}"></script>
        
{% endblock edge %}

bbs/templates/bbs/free.html
{% extends "bbs/base.html" %}
{% block content %}
<div class="row d-flex justify-content-center">
    <div class="col-10">
        <br>
        <h1 class="h1 mb-3" style="font-family: 'Poor Story', cursive; font-size : 70px; font-weight: bold;"><i data-feather="align-left"></i> 자유게시판</h1>
        
        <br>
        <div class="row">
            {%for list in postlist%}
            <div class="col-md-4 col-sm-4 b">
                <br>
                <div class="card">
                    <div class="card-header">
                        <small># {{list.id}}번 째 게시글</small>
                        <a href="{{list.pk}}/">
                                <h1 style="font-family: 'Dongle', sans-serif; color: #3A3A51; ">
                                        {{list.postname|truncatechars:17}}
                                </h1>
                        </a>
                        
                    </div>
                    <div class="card-body">
                        {{list.contents|safe|striptags|truncatechars:20}}
                    </div>
                    <div class="card-footer">
                    <h5 style="float:right"><small>조회 수 : {{ list.views }}</small></h5>
                    </div>
                </div>
            </div>
            {% endfor %}
            
        </div>
            {% if user.is_authenticated %}
                <!--{{ user.username }}--> 
                <div class="d-grid gap-2 d-md-flex justify-content-md-end mt-5">
                <a class="btn btn-primary" href="new_post/{{user.username}}/" role="button">글쓰기</a>
                </div>
            {% endif %}
        <!-- 페이징 관련 -->
        <div class="d-flex justify-content-between mt-3">
            <!-- 이전페이지 -->
            {% if postlist.has_previous %}
                <a href="?page={{ postlist.previous_page_number }}">이전</a>
            {% else %}
                <a tabindex="-1" aria-disabled="true" href="#">이전</a>
            {% endif %}
            <!-- 페이지리스트 -->
            <div class="d-flex justify-content-center">
                
                {% for page_number in postlist.paginator.page_range %}
                    {% if page_number >= postlist.number|add:-2 and page_number <= postlist.number|add:2 %}
                        {% if page_number == postlist.number %}
                            <!-- 현재 페이지 -->
                            <button class="btn btn-primary" onclick="location.href = '?page={{ page_number }}'">
                                {{ page_number }}
                            </button>
                        {% else %}
                        <button class="btn btn-outline-primary" onclick="location.href = '?page={{ page_number }}'">
                            {{ page_number }}
                        </button>
                        {% endif %}
                    {% endif %}
                {% endfor %}
            </div>
                <!-- 다음페이지 -->
                {% if postlist.has_next %}
                    <a href="?page={{ postlist.next_page_number }}">다음</a>
                {% else %}
                    <a tabindex="-1" aria-disabled="true" href="#">다음</a>
                
                {% endif %}
        </div>

    </div>
</div>
{% endblock %}

bbs/templates/bbs/posting.html
{% extends "bbs/base.html" %}
{% block content %}
<link rel="stylesheet"
      href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.4.0/styles/atom-one-dark.min.css">
<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.4.0/highlight.min.js"></script>
<script>hljs.highlightAll();</script>

<div class="container my-3">
    <br><br>
    
        <p class="fs-4" style="float:right"><small>조회 수 : {{ post.views }}</small></p>
    
    
    <h2 class="border-bottom py-2"style="font-family: 'Poor Story', cursive; font-size : 70px; font-weight: bold;">{{ post.postname }}</h2>
    <h5> 작성자 : {{ post.writer }}</h5>
        <div class="card my-3">
            <div class="card-body">
                <div class="card-text" style="white-space: pre-line;">
                    {{ post.contents|safe }}
                </div>
                <br>
                {% if post.code_edit != '' %}
            </div>
        </div>
        {% comment %} <div class="btn-group" role="group" aria-label="Basic radio toggle button group">
            <input type="radio" class="btn-check" onclick="ChangePython()" name="btnradio" id="btnradio1" autocomplete="off" checked>
            <label class="btn btn-outline-primary" for="btnradio1">Python</label>
            <input type="radio" class="btn-check" onclick="ChangeJava()" name="btnradio" id="btnradio2" autocomplete="off">
            <label class="btn btn-outline-primary" for="btnradio2">JAVA</label>
            <input type="radio" class="btn-check" onclick="ChangeCpp()" name="btnradio" id="btnradio3" autocomplete="off">
            <label class="btn btn-outline-primary" for="btnradio3">C++</label>
        </div>
        <pre><code id="output" class="python">{{ post.code_edit }}</code></pre> {% endcomment %}
    {% endif %}
    
        <script>
            var outputarea = document.getElementById("output");
            function ChangePython(){
                outputarea.className = 'Python';
                hljs.highlightBlock(outputarea);
            }
            function ChangeJava(){
                outputarea.className = 'JAVA';
                hljs.highlightBlock(outputarea);
            }
            function ChangeCpp(){
                outputarea.className = 'cpp';
                hljs.highlightBlock(outputarea);
            }
        </script>    
    
    {% for uploadfile in post.uploadfile_set.all %}
    {% csrf_token %}
        <td>
            <i data-feather="download"></i>
            <a class="btn" href="/free/{{uploadfile.id}}/download/" role="button"> 
                <h5>
                    {{ uploadfile.file }}
                </h5> 
            </a>
        </td>
    {% endfor %}

    <h5 class="border-bottom my-3 py-2">
        {{post.comment_set.count}}개의 답변이 있습니다.
    </h5>

    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">내용</th>
                <th scope="col">시간</th>
                <th scope="col">   </th>
            </tr>
        </thead>
        <tbody>
            {% for comment in post.comment_set.all %}
            <tr>
            {% csrf_token %}
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ comment.content }}</td>
                <td>{{ comment.create_date }}</td>
                <td>
                    {% if user.is_authenticated %}
                        <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#삭제1">
                            삭제
                        </button>
                        <div class="modal fade" id="삭제1" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="staticBackdropLabel">정말로 이 댓글을 삭제하시겠습니까?</h5>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                        {{comment.content}}
                                    </div>
                                    <div class="modal-footer">
                                        <a class="btn btn-danger" href="/free/{{post.id}}/{{comment.id}}/" role="button">삭제</a>
                                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">취소</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody> 
    </table>
    
 

    <form action="{% url 'bbs:comment_create' post.id %}"
        method="post" class="my-3">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
            <div class="alert alert-danger" role="alert">
            {% for field in form %}
                {% if field.errors %}
                    <strong>{{ field.label }}</strong>
                    {{ field.errors }}
                {% endif %}
            {% endfor %}
            </div>
        {% endif %}
        <!-- 오류표시 End -->

        <div class="form-group">
            <textarea name="content" id="content" class="form-control" rows="5"></textarea>
        </div>
        <br>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>

    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <a class="btn btn-primary" href="/free/" role="button">목록</a>
        {% if post.writer == user.username %}
            <a class="btn btn-danger" href="/free/{{post.pk}}/remove/" role="button">삭제</a>
        {% endif %}
    </div>
    
</div>
</div>
{% endblock %}

bbs/templates/bbs/remove_post.html
{% extends "bbs/base.html" %}
{% block content %}
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col">
      <form method="POST">
      {% csrf_token %}
        <div class="card text-center">
          <div class="card-header">
            <h2> {{Post.postname}} 삭제</h2>
          </div>
          <div class="card-body">
            <h5 class="card-title">
              <p class="text-black">
                정말 삭제하시겠습니까?
              </p>
            </h5>
            <button type="submit" class="btn btn-danger">삭제</button>
            <a class="btn btn-secondary" href="/free/{{Post.pk}}/" role="button">취소</a>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}

bbs/templates/bbs/upload.html
<form action="{% url 'qua/new_post/1/upload' %}" method="post"
        enctype="multipart/form-data">
    
        {% csrf_token %}
    <input type="file" name="file">
    <input type="submit" value="전송">
</form>